# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: local
    hooks:
      - id: check-format
        name: check-format
        entry: poetry run poe check-format-pre-commit
        language: system
        types: [ python ]
        require_serial: true
      - id: check-lint
        name: check-lint
        entry: poetry run poe check-lint-pre-commit
        language: system
        types: [ python ]
        require_serial: true
      - id: check-types
        name: check-types
        entry: poetry run poe check-types-pre-commit
        language: system
        types: [ python ]
        require_serial: true
