# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [python]
        require_serial: true
